from src.chemistry.loaders.species import load_species
from src.constants.constants import ASSETS
def register_species():
    load_species(str(ASSETS / "chem" / "species"))
"""def register_species():
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="Na",
            formula="Na",
            name="Sodium",
            charge=1,
            oxidation_states=(1,),
            category=Category.ALKALI_METAL,
            tier=1,
            score=10,
            spawn_weight=10,
            can_spawn=True,
        )
    )

    SpeciesRegistry.register(
        ReactiveSpecies(
            id="Cl",
            formula="Cl",
            name="Chloride",
            charge=-1,
            oxidation_states=(-1,),
            category=Category.HALOGEN,
            tier=1,
            score=10,
            spawn_weight=10,
            can_spawn=True,
        )
    )

    SpeciesRegistry.register(
        FinishedCompound(
            id="NaCl",
            formula="NaCl",
            name="Sodium Chloride",
            tier=1,
            score=10,
            can_keep=False,
            category=Category.SALT,
            can_spawn=False,
            points=10
        )
    )
    
    SpeciesRegistry.register(
        FinishedCompound(
            id="Cl2",
            formula="Cl₂",
            name="Diatomic Chlorine",
            tier=1,
            score=10,
            can_keep=False,
            category=Category.HALOGEN,
            can_spawn=False,
            points=10
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="O",
            formula="O",
            name="Oxygen",
            tier=1,
            score=10,
            category=Category.CHALCOGEN,
            can_spawn=True,
            charge=-2,
            oxidation_states=(-2,),
            spawn_weight=10
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="O2",
            formula="O₂",
            name="Diatomic Oxygen",
            tier=1,
            score=10,
            can_keep=False,
            category=Category.CHALCOGEN,
            can_spawn=False,
            points=10
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="NaO",
            formula="NaO",
            name="Sodium Monoxide Ion",
            tier=1,
            score=10,
            category=Category.POLYATOMIC_ANION,
            can_spawn=False,
            charge=-1,
            oxidation_states=(-1,),
            spawn_weight=10
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="Na2O",
            formula="Na₂O",
            name="Sodium Oxide",
            tier=1,
            score=20,
            category=Category.SALT,
            can_spawn=False,
            can_keep=False
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="NaClO",
            formula="NaClO",
            name="Sodium Hypochlorite",
            tier=1,
            score=20,
            category=Category.SALT,
            can_spawn=False,
            can_keep=False
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="NaClO2",
            formula="NaClO₂",
            name="Sodium Chlorite",
            tier=1,
            score=30,
            category=Category.SALT,
            can_spawn=False,
            can_keep=False
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="NaClO3",
            formula="NaClO₃",
            name="Sodium Chlorate",
            tier=1,
            score=50,
            category=Category.SALT,
            can_spawn=False,
            can_keep=False
        )
    )
    SpeciesRegistry.register(
        FinishedCompound(
            id="NaClO4",
            formula="NaClO₄",
            name="Sodium Perchlorate",
            tier=1,
            score=70,
            category=Category.SALT,
            can_spawn=False,
            can_keep=False
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="ClO",
            formula="ClO",
            name="Hypochlorite",
            tier=1,
            score=10,
            category=Category.POLYATOMIC_ANION,
            can_spawn=False,
            charge=-1,
            oxidation_states=(-1,),
            spawn_weight=10
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="ClO2",
            formula="ClO₂",
            name="Chlorite",
            tier=1,
            score=10,
            category=Category.POLYATOMIC_ANION,
            can_spawn=False,
            charge=-1,
            oxidation_states=(-1,),
            spawn_weight=10
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="ClO3",
            formula="ClO₃",
            name="Chlorate",
            tier=1,
            score=10,
            category=Category.POLYATOMIC_ANION,
            can_spawn=False,
            charge=-1,
            oxidation_states=(-1,),
            spawn_weight=10
        )
    )
    SpeciesRegistry.register(
        ReactiveSpecies(
            id="ClO4",
            formula="ClO₄",
            name="Perchlorate",
            tier=1,
            score=10,
            category=Category.POLYATOMIC_ANION,
            can_spawn=False,
            charge=-1,
            oxidation_states=(-1,),
            spawn_weight=10
        )
    )"""